number_of_events: 1
number_of_bunchs: 1


some_paths:
  CVMFS: "/cvmfs/lhcb.cern.ch/lib/lhcb/"
  APPCONFIGOPTS: "{cvmfs}/DBASE/AppConfig/v3r403/options"
  DECFILESROOT : "{cvmfs}/DBASE/Gen/DecFiles/{decfiles_version}"

general:
  decfiles_version: 'v30r66'
  appconfig_version: 'v3r403'

general_config: &general_config
  decfiles_version: 'v30r55'
  appconfig_version: 'v3r403'

2015:
  <<: *general_config 
  stripping_version: '28r2'

2016:
  <<: *general_config 
  stripping_version: '28r2'

2017:
  <<: *general_config 
  stripping_version: '28r2'

2018:
  <<: *general_config 
  stripping_version: '28r2'
